### ISSUE TITLE
Рефакторинг

### ISSUE THREAD

**Issue by WaveCutz** [WaveCutz/habrahabr.ru_night-mode#23]
@extempl Есть мнение, что надо замутить рефакторинг. Использовать исходник в виде какого нибудь модного компилируемого фреймворка, например, [Stylus](http://stylus-lang.com/). Убрать deprecated вещи. Ведь верстка хабра очень эволюционировала с момента создания юзерскрита. Есть мысли, возражения?

**Comment by extempl** [comment]
А в чём смысл использовать препроцессор здесь? Только для более компактной записи фильтров для картинок? Можно было бы ещё вложенность заюзать, например, для многочисленных стилей кода, но там цвета так переплетены, что их придётся дублировать. Или записывать так, как они сейчас есть - один цвет, и все встречающиеся места через запятую.
Ещё вынести список цветов в переменных в топ - но при такой частоте обновления профит сомнительный.
Хотя, если вложенность использовать вместе с переменными, то можно получить красивое дерево в исходнике и скомпилированный файл, как он есть сейчас.

На счёт рефакторинга в целом и пересмотра неактуальных селекторов - за.

**Comment by WaveCutz** [comment]
@extempl Да, я именно за вынос переменных и удобную группировку, миксины, ибо уже сам теряюсь во всех цветах и группах элементов.

**Comment by extempl** [comment]
Попробовал перенести на Stylus - я бы всё-таки отдал предпочтение SASS, там переменные, миксины и плейсхолдеры понятнее оформлены, как определение, так и использование.

**Comment by extempl** [comment]
https://github.com/WaveCutz/habrahabr.ru_night-mode/pull/24
