### ISSUE TITLE
TMpanel перекрывает логотип

### ISSUE THREAD

**Issue by lucky-user** [WaveCutz/habrahabr.ru_night-mode#25]
Ломается на ревизии e7586f68bfd5f7e409199390ce65ac0a7bed7088

![скрин](https://s22.postimg.org/llh05mi29/NM-bug.png)

**Comment by WaveCutz** [comment]
@extempl поломаль?:)

**Comment by WaveCutz** [comment]
@extempl у меня воспроизводится, до начала скролла. Chrome dev

**Comment by extempl** [comment]
Пофиксил.
